/**
 * Canonical list of common academic departments across universities worldwide.
 * Used as suggestions in the department autocomplete.
 * All entries are already Title Case — no further normalization needed.
 */
export const COMMON_DEPARTMENTS: string[] = [
  'Accounting',
  'Agricultural Sciences',
  'Architecture',
  'Biochemistry',
  'Biology',
  'Biomedical Engineering',
  'Business Administration',
  'Chemical Engineering',
  'Chemistry',
  'Civil Engineering',
  'Communication Studies',
  'Computer Engineering',
  'Computer Science',
  'Criminology',
  'Dentistry',
  'Economics',
  'Education',
  'Electrical Engineering',
  'English Language',
  'Environmental Science',
  'Finance',
  'Geography',
  'History',
  'Human Resource Management',
  'Industrial Engineering',
  'Information Technology',
  'International Relations',
  'Law',
  'Linguistics',
  'Marketing',
  'Mathematics',
  'Mechanical Engineering',
  'Medicine',
  'Microbiology',
  'Nursing',
  'Optometry',
  'Petroleum Engineering',
  'Pharmacy',
  'Philosophy',
  'Physics',
  'Political Science',
  'Psychology',
  'Public Administration',
  'Public Health',
  'Radiography',
  'Sociology',
  'Software Engineering',
  'Statistics',
  'Urban Planning',
  'Veterinary Medicine',
];
